mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
#  type-aliases-package: com.shendun.hotel.springbootproject.
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1

server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #数据库url
    url: jdbc:mysql://localhost:3306/lh_database?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull
    # 数据库访问账户
    username: root
    # 数据库访问密码
    password: 1234QWERt-
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                  # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                # 最大的连接数
      max-wait-millis: 60000 				# 等待连接获取的最大超时时间
  #集中解决各种编码问题
  banner:
    charset: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # 时间格式化
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    # 时区设置
#    time-zone: GMT+8